// Generated by gencpp from file cob_3d_mapping_msgs/GetObjectsOfClassRequest.msg
// DO NOT EDIT!


#ifndef COB_3D_MAPPING_MSGS_MESSAGE_GETOBJECTSOFCLASSREQUEST_H
#define COB_3D_MAPPING_MSGS_MESSAGE_GETOBJECTSOFCLASSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/UInt32.h>

namespace cob_3d_mapping_msgs
{
template <class ContainerAllocator>
struct GetObjectsOfClassRequest_
{
  typedef GetObjectsOfClassRequest_<ContainerAllocator> Type;

  GetObjectsOfClassRequest_()
    : class_id()  {
    }
  GetObjectsOfClassRequest_(const ContainerAllocator& _alloc)
    : class_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::UInt32_<ContainerAllocator>  _class_id_type;
  _class_id_type class_id;





  typedef boost::shared_ptr< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetObjectsOfClassRequest_

typedef ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<std::allocator<void> > GetObjectsOfClassRequest;

typedef boost::shared_ptr< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest > GetObjectsOfClassRequestPtr;
typedef boost::shared_ptr< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest const> GetObjectsOfClassRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator1> & lhs, const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator2> & rhs)
{
  return lhs.class_id == rhs.class_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator1> & lhs, const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_3d_mapping_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cd17435496133fe7b904bdd1a1f66ee";
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cd17435496133feULL;
  static const uint64_t static_value2 = 0x7b904bdd1a1f66eeULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_3d_mapping_msgs/GetObjectsOfClassRequest";
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/UInt32 class_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt32\n"
"uint32 data\n"
;
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetObjectsOfClassRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest_<ContainerAllocator>& v)
  {
    s << indent << "class_id: ";
    s << std::endl;
    Printer< ::std_msgs::UInt32_<ContainerAllocator> >::stream(s, indent + "  ", v.class_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_3D_MAPPING_MSGS_MESSAGE_GETOBJECTSOFCLASSREQUEST_H
