// Generated by gencpp from file seher_support/PoseStampedArray.msg
// DO NOT EDIT!


#ifndef SEHER_SUPPORT_MESSAGE_POSESTAMPEDARRAY_H
#define SEHER_SUPPORT_MESSAGE_POSESTAMPEDARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace seher_support
{
template <class ContainerAllocator>
struct PoseStampedArray_
{
  typedef PoseStampedArray_<ContainerAllocator> Type;

  PoseStampedArray_()
    : stamped_poses()  {
    }
  PoseStampedArray_(const ContainerAllocator& _alloc)
    : stamped_poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _stamped_poses_type;
  _stamped_poses_type stamped_poses;





  typedef boost::shared_ptr< ::seher_support::PoseStampedArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seher_support::PoseStampedArray_<ContainerAllocator> const> ConstPtr;

}; // struct PoseStampedArray_

typedef ::seher_support::PoseStampedArray_<std::allocator<void> > PoseStampedArray;

typedef boost::shared_ptr< ::seher_support::PoseStampedArray > PoseStampedArrayPtr;
typedef boost::shared_ptr< ::seher_support::PoseStampedArray const> PoseStampedArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seher_support::PoseStampedArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seher_support::PoseStampedArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seher_support::PoseStampedArray_<ContainerAllocator1> & lhs, const ::seher_support::PoseStampedArray_<ContainerAllocator2> & rhs)
{
  return lhs.stamped_poses == rhs.stamped_poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seher_support::PoseStampedArray_<ContainerAllocator1> & lhs, const ::seher_support::PoseStampedArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seher_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::seher_support::PoseStampedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seher_support::PoseStampedArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seher_support::PoseStampedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seher_support::PoseStampedArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seher_support::PoseStampedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seher_support::PoseStampedArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seher_support::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06f872dd9a9374c503dfaed9499d3a21";
  }

  static const char* value(const ::seher_support::PoseStampedArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06f872dd9a9374c5ULL;
  static const uint64_t static_value2 = 0x03dfaed9499d3a21ULL;
};

template<class ContainerAllocator>
struct DataType< ::seher_support::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seher_support/PoseStampedArray";
  }

  static const char* value(const ::seher_support::PoseStampedArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seher_support::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped[] stamped_poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::seher_support::PoseStampedArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seher_support::PoseStampedArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamped_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseStampedArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seher_support::PoseStampedArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seher_support::PoseStampedArray_<ContainerAllocator>& v)
  {
    s << indent << "stamped_poses[]" << std::endl;
    for (size_t i = 0; i < v.stamped_poses.size(); ++i)
    {
      s << indent << "  stamped_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.stamped_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEHER_SUPPORT_MESSAGE_POSESTAMPEDARRAY_H
