// Generated by gencpp from file cob_object_detection_msgs/BagTrainObjectResponse.msg
// DO NOT EDIT!


#ifndef COB_OBJECT_DETECTION_MSGS_MESSAGE_BAGTRAINOBJECTRESPONSE_H
#define COB_OBJECT_DETECTION_MSGS_MESSAGE_BAGTRAINOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace cob_object_detection_msgs
{
template <class ContainerAllocator>
struct BagTrainObjectResponse_
{
  typedef BagTrainObjectResponse_<ContainerAllocator> Type;

  BagTrainObjectResponse_()
    : trained()  {
    }
  BagTrainObjectResponse_(const ContainerAllocator& _alloc)
    : trained(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _trained_type;
  _trained_type trained;





  typedef boost::shared_ptr< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BagTrainObjectResponse_

typedef ::cob_object_detection_msgs::BagTrainObjectResponse_<std::allocator<void> > BagTrainObjectResponse;

typedef boost::shared_ptr< ::cob_object_detection_msgs::BagTrainObjectResponse > BagTrainObjectResponsePtr;
typedef boost::shared_ptr< ::cob_object_detection_msgs::BagTrainObjectResponse const> BagTrainObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator1> & lhs, const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.trained == rhs.trained;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator1> & lhs, const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_object_detection_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a94192f68364f039ed20f2ad560e48fd";
  }

  static const char* value(const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa94192f68364f039ULL;
  static const uint64_t static_value2 = 0xed20f2ad560e48fdULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_object_detection_msgs/BagTrainObjectResponse";
  }

  static const char* value(const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String trained\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trained);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BagTrainObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_object_detection_msgs::BagTrainObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "trained: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.trained);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_OBJECT_DETECTION_MSGS_MESSAGE_BAGTRAINOBJECTRESPONSE_H
