// Generated by gencpp from file cob_object_detection_msgs/SaveRecordedObjectRequest.msg
// DO NOT EDIT!


#ifndef COB_OBJECT_DETECTION_MSGS_MESSAGE_SAVERECORDEDOBJECTREQUEST_H
#define COB_OBJECT_DETECTION_MSGS_MESSAGE_SAVERECORDEDOBJECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_object_detection_msgs
{
template <class ContainerAllocator>
struct SaveRecordedObjectRequest_
{
  typedef SaveRecordedObjectRequest_<ContainerAllocator> Type;

  SaveRecordedObjectRequest_()
    : storage_location()  {
    }
  SaveRecordedObjectRequest_(const ContainerAllocator& _alloc)
    : storage_location(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _storage_location_type;
  _storage_location_type storage_location;





  typedef boost::shared_ptr< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveRecordedObjectRequest_

typedef ::cob_object_detection_msgs::SaveRecordedObjectRequest_<std::allocator<void> > SaveRecordedObjectRequest;

typedef boost::shared_ptr< ::cob_object_detection_msgs::SaveRecordedObjectRequest > SaveRecordedObjectRequestPtr;
typedef boost::shared_ptr< ::cob_object_detection_msgs::SaveRecordedObjectRequest const> SaveRecordedObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator1> & lhs, const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.storage_location == rhs.storage_location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator1> & lhs, const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_object_detection_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "980da3132a7c1c17973e490fc0fbba86";
  }

  static const char* value(const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x980da3132a7c1c17ULL;
  static const uint64_t static_value2 = 0x973e490fc0fbba86ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_object_detection_msgs/SaveRecordedObjectRequest";
  }

  static const char* value(const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
"string storage_location\n"
;
  }

  static const char* value(const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.storage_location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveRecordedObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_object_detection_msgs::SaveRecordedObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "storage_location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.storage_location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_OBJECT_DETECTION_MSGS_MESSAGE_SAVERECORDEDOBJECTREQUEST_H
