// Generated by gencpp from file cob_object_detection_msgs/StopObjectRecordingRequest.msg
// DO NOT EDIT!


#ifndef COB_OBJECT_DETECTION_MSGS_MESSAGE_STOPOBJECTRECORDINGREQUEST_H
#define COB_OBJECT_DETECTION_MSGS_MESSAGE_STOPOBJECTRECORDINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_object_detection_msgs
{
template <class ContainerAllocator>
struct StopObjectRecordingRequest_
{
  typedef StopObjectRecordingRequest_<ContainerAllocator> Type;

  StopObjectRecordingRequest_()
    : stop_although_model_is_incomplete(false)  {
    }
  StopObjectRecordingRequest_(const ContainerAllocator& _alloc)
    : stop_although_model_is_incomplete(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stop_although_model_is_incomplete_type;
  _stop_although_model_is_incomplete_type stop_although_model_is_incomplete;





  typedef boost::shared_ptr< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopObjectRecordingRequest_

typedef ::cob_object_detection_msgs::StopObjectRecordingRequest_<std::allocator<void> > StopObjectRecordingRequest;

typedef boost::shared_ptr< ::cob_object_detection_msgs::StopObjectRecordingRequest > StopObjectRecordingRequestPtr;
typedef boost::shared_ptr< ::cob_object_detection_msgs::StopObjectRecordingRequest const> StopObjectRecordingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator1> & lhs, const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.stop_although_model_is_incomplete == rhs.stop_although_model_is_incomplete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator1> & lhs, const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_object_detection_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60ec7755ba9c0b6779b757eba0e03e82";
  }

  static const char* value(const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60ec7755ba9c0b67ULL;
  static const uint64_t static_value2 = 0x79b757eba0e03e82ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_object_detection_msgs/StopObjectRecordingRequest";
  }

  static const char* value(const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
"bool stop_although_model_is_incomplete\n"
;
  }

  static const char* value(const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop_although_model_is_incomplete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopObjectRecordingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_object_detection_msgs::StopObjectRecordingRequest_<ContainerAllocator>& v)
  {
    s << indent << "stop_although_model_is_incomplete: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop_although_model_is_incomplete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_OBJECT_DETECTION_MSGS_MESSAGE_STOPOBJECTRECORDINGREQUEST_H
