// Generated by gencpp from file cob_people_detection/getDetectionsGoal.msg
// DO NOT EDIT!


#ifndef COB_PEOPLE_DETECTION_MESSAGE_GETDETECTIONSGOAL_H
#define COB_PEOPLE_DETECTION_MESSAGE_GETDETECTIONSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_people_detection
{
template <class ContainerAllocator>
struct getDetectionsGoal_
{
  typedef getDetectionsGoal_<ContainerAllocator> Type;

  getDetectionsGoal_()
    : maximum_message_age(0.0)
    , timeout(0.0)  {
    }
  getDetectionsGoal_(const ContainerAllocator& _alloc)
    : maximum_message_age(0.0)
    , timeout(0.0)  {
  (void)_alloc;
    }



   typedef float _maximum_message_age_type;
  _maximum_message_age_type maximum_message_age;

   typedef float _timeout_type;
  _timeout_type timeout;





  typedef boost::shared_ptr< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct getDetectionsGoal_

typedef ::cob_people_detection::getDetectionsGoal_<std::allocator<void> > getDetectionsGoal;

typedef boost::shared_ptr< ::cob_people_detection::getDetectionsGoal > getDetectionsGoalPtr;
typedef boost::shared_ptr< ::cob_people_detection::getDetectionsGoal const> getDetectionsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator1> & lhs, const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.maximum_message_age == rhs.maximum_message_age &&
    lhs.timeout == rhs.timeout;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator1> & lhs, const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_people_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd64e18e045dc05a5cb38c8f05510e32";
  }

  static const char* value(const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd64e18e045dc05aULL;
  static const uint64_t static_value2 = 0x5cb38c8f05510e32ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_people_detection/getDetectionsGoal";
  }

  static const char* value(const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"float32 maximum_message_age		# maximal allowed age of response message (in s), 0 means we do not care\n"
"float32 timeout				# maximal waiting time (in s) for receiving a detection, 0 is infinitely. If the detection pipeline was not running before, it will start upon receiving this message and collect messages for the full timeout period.\n"
;
  }

  static const char* value(const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.maximum_message_age);
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getDetectionsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_people_detection::getDetectionsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_people_detection::getDetectionsGoal_<ContainerAllocator>& v)
  {
    s << indent << "maximum_message_age: ";
    Printer<float>::stream(s, indent + "  ", v.maximum_message_age);
    s << indent << "timeout: ";
    Printer<float>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_PEOPLE_DETECTION_MESSAGE_GETDETECTIONSGOAL_H
