// Generated by gencpp from file cob_people_detection/loadModelGoal.msg
// DO NOT EDIT!


#ifndef COB_PEOPLE_DETECTION_MESSAGE_LOADMODELGOAL_H
#define COB_PEOPLE_DETECTION_MESSAGE_LOADMODELGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_people_detection
{
template <class ContainerAllocator>
struct loadModelGoal_
{
  typedef loadModelGoal_<ContainerAllocator> Type;

  loadModelGoal_()
    : labels()  {
    }
  loadModelGoal_(const ContainerAllocator& _alloc)
    : labels(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _labels_type;
  _labels_type labels;





  typedef boost::shared_ptr< ::cob_people_detection::loadModelGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_people_detection::loadModelGoal_<ContainerAllocator> const> ConstPtr;

}; // struct loadModelGoal_

typedef ::cob_people_detection::loadModelGoal_<std::allocator<void> > loadModelGoal;

typedef boost::shared_ptr< ::cob_people_detection::loadModelGoal > loadModelGoalPtr;
typedef boost::shared_ptr< ::cob_people_detection::loadModelGoal const> loadModelGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_people_detection::loadModelGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_people_detection::loadModelGoal_<ContainerAllocator1> & lhs, const ::cob_people_detection::loadModelGoal_<ContainerAllocator2> & rhs)
{
  return lhs.labels == rhs.labels;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_people_detection::loadModelGoal_<ContainerAllocator1> & lhs, const ::cob_people_detection::loadModelGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_people_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_people_detection::loadModelGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_people_detection::loadModelGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_people_detection::loadModelGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17b562487ca772bdfa2c078ef00d870f";
  }

  static const char* value(const ::cob_people_detection::loadModelGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17b562487ca772bdULL;
  static const uint64_t static_value2 = 0xfa2c078ef00d870fULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_people_detection/loadModelGoal";
  }

  static const char* value(const ::cob_people_detection::loadModelGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Loads a recognition model for the face recognizer from disc or database\n"
"#\n"
"# goal message\n"
"string[] labels		# a list of labels of persons that shall be recognized\n"
;
  }

  static const char* value(const ::cob_people_detection::loadModelGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.labels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct loadModelGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_people_detection::loadModelGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_people_detection::loadModelGoal_<ContainerAllocator>& v)
  {
    s << indent << "labels[]" << std::endl;
    for (size_t i = 0; i < v.labels.size(); ++i)
    {
      s << indent << "  labels[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.labels[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_PEOPLE_DETECTION_MESSAGE_LOADMODELGOAL_H
